-- MySQL Script generated by MySQL Workbench
-- Fri Oct 29 18:56:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca_musical
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca_musical
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_musical` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca_musical` ;

-- -----------------------------------------------------
-- Table `biblioteca_musical`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_musical`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre_genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE INDEX `nombre_genero_UNIQUE` (`nombre_genero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_musical`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_musical`.`artista` (
  `id_artista` INT NOT NULL AUTO_INCREMENT,
  `nombre_artista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_artista`),
  UNIQUE INDEX `nombre_artista_UNIQUE` (`nombre_artista` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_musical`.`cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_musical`.`cancion` (
  `id_cancion` INT NOT NULL AUTO_INCREMENT,
  `nombre_cancion` VARCHAR(45) NOT NULL,
  `duracion_cancion` VARCHAR(45) NOT NULL,
  `ruta_cancion` VARCHAR(255) NOT NULL,
  `genero_id_genero` INT NULL,
  `artista_id_artista` INT NULL,
  PRIMARY KEY (`id_cancion`),
  INDEX `fk_cancion_genero_idx` (`genero_id_genero` ASC) VISIBLE,
  INDEX `fk_cancion_artista1_idx` (`artista_id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_cancion_genero`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `biblioteca_musical`.`genero` (`id_genero`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cancion_artista1`
    FOREIGN KEY (`artista_id_artista`)
    REFERENCES `biblioteca_musical`.`artista` (`id_artista`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_musical`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_musical`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `nombre_album` VARCHAR(45) NOT NULL,
  `ruta_portada` VARCHAR(255) NOT NULL,
  `año` INT NOT NULL,
  PRIMARY KEY (`id_album`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_musical`.`album_cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_musical`.`album_cancion` (
  `cancion_id_cancion` INT NOT NULL,
  `album_id_album` INT NOT NULL,
  INDEX `fk_album_cancion_cancion1_idx` (`cancion_id_cancion` ASC) VISIBLE,
  INDEX `fk_album_cancion_album1_idx` (`album_id_album` ASC) VISIBLE,
  CONSTRAINT `fk_album_cancion_cancion1`
    FOREIGN KEY (`cancion_id_cancion`)
    REFERENCES `biblioteca_musical`.`cancion` (`id_cancion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_album_cancion_album1`
    FOREIGN KEY (`album_id_album`)
    REFERENCES `biblioteca_musical`.`album` (`id_album`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_musical`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_musical`.`playlist` (
  `id_playlist` INT NOT NULL AUTO_INCREMENT,
  `nombre_playlist` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_playlist`),
  UNIQUE INDEX `nombre_playlist_UNIQUE` (`nombre_playlist` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_musical`.`playlist_cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_musical`.`playlist_cancion` (
  `cancion_id_cancion` INT NOT NULL,
  `playlist_id_playlist` INT NOT NULL,
  INDEX `fk_playlist_cancion_cancion1_idx` (`cancion_id_cancion` ASC) VISIBLE,
  INDEX `fk_playlist_cancion_playlist1_idx` (`playlist_id_playlist` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_cancion_cancion1`
    FOREIGN KEY (`cancion_id_cancion`)
    REFERENCES `biblioteca_musical`.`cancion` (`id_cancion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_playlist_cancion_playlist1`
    FOREIGN KEY (`playlist_id_playlist`)
    REFERENCES `biblioteca_musical`.`playlist` (`id_playlist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
